version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        mode: non-blocking
        max-buffer-size: 4m
    depends_on:
      - loki

  loki:
    image: grafana/loki:2.9.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:10.0.0
    ports:
      - "3000:3000"
    depends_on:
      - loki
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
